### ISSUE TITLE
too difficult to scrape timeseries data?

### ISSUE THREAD

**Issue by aminadibi** [mattkerlogue/google-covid-mobility-scrape#1]
Would be hugely useful to be able to see trends

**Comment by mattkerlogue** [comment]
The ONS Data Science Campus have developed code to extract the trend lines see this repo: https://github.com/datasciencecampus/mobility-report-data-extractor

**Comment by mattkerlogue** [comment]
To note, the [README](https://github.com/mattkerlogue/google-covid-mobility-scrape/blob/master/README.md) has now been updated with links to the ONS time-series extractor in both its native Python coding and a port to R.
